config/routes.rb
Rails.application.routes.draw do
  resources :links
  resources :categories

  root to: 'links#index'

  get 'links/index'

  get 'links/new'

  get 'links/create'

  get 'links/destroy'

  get 'links/edit'

  get 'links/update'

  get 'links/check-read/:id/:read', to: 'links#check_read'

  get 'links/preview/*url', to: 'links#preview'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord

    def to_str
        @name
    end

end

app/models/link-preview.rb
require 'open-uri'
class LinkPreview

    def initialize(url)
        @url = filter_url(url)
    end
    
    def metadata
        new_url = "https://" + @url
        begin
            @doc = Nokogiri::HTML(open(new_url))
            params = {
                image: get_image,
                description: get_description,
                title: get_title
            }
        rescue
            puts "Não foi possível realizar a conexão com o endereço #{@url}"
        end
    end

    def get_image
        content = get_content "meta[property='og:image']"
        if content.present?
            content.values[1]
        end
    end

    def get_description
        content = get_content "meta[property='description']"
        if content.present?
            content.values[1]
        else
            content = get_content "meta[property='og:description']"
            if content.present?
                content.values[1]
            end
        end
    end

    def get_title
        content = get_content "title"
        content.text
    end

    def get_content(selector)
        doc = @doc.search("head #{selector}")
        doc.first
    end

    def filter_url(url)
        url = url.sub(/https:(\/+)www\./, '') 
        url = url.sub(/http:(\/+)www\./, '')
        url = url.sub(/https:(\/+)/, '')
        url = url.sub(/http:(\/+)/, '')
        url
    end


end

app/models/link.rb
class Link < ApplicationRecord
  belongs_to :category

  def self.search(title)
    if(title)
      where('title LIKE ?', "%#{title}%").order("read ASC")
    else
      order("read ASC")
    end
  end

  def self.preview(url)
    require('link-preview')
    linkPreview = LinkPreview.new(url)
    linkPreview.metadata
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Categoria criada!' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Categoria atualizada!' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Categoria excluída!' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:show, :edit, :update, :destroy]

  # GET /links
  # GET /links.json
  def index
    @links = Link.search(params[:title])
  end

  # GET /links/1
  # GET /links/1.json
  def show
  end

  # GET /links/new
  def new
    @link = Link.new
  end

  # GET /links/1/edit
  def edit
  end

  # POST /links
  # POST /links.json
  def create
    @link = Link.new(link_params)

    respond_to do |format|
      if @link.save
        format.html { redirect_to links_path, notice: 'Link criado com sucesso!' }
        format.json { render :show, status: :created, location: @link }
      else
        format.html { render :new }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /links/1
  # PATCH/PUT /links/1.json
  def update
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to @link, notice: 'Link atualizado com sucesso!' }
        format.json { render :show, status: :ok, location: @link }
      else
        format.html { render :edit }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /links/1/true
  def check_read
	  @link = Link.find(params[:id])
	  @link.update(read: params[:read])
	  render json: @link
  end

  # GET /links/preview/url
  def preview
    print params[:url].html_safe
    preview = Link.preview(params[:url].html_safe)
    render json: preview
  end

  # DELETE /links/1
  # DELETE /links/1.json
  def destroy
    @link.destroy
    respond_to do |format|
      format.html { redirect_to links_url, notice: 'Link excluído com sucesso!' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link
      @link = Link.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def link_params
      params.require(:link).permit(:title, :url, :read, :category_id, :id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

    def readable_boolean(boolean)
        boolean ? 'Sim' : 'Não'
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :category_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Alterando Categoria</h1>

<%= render 'form', category: @category %>

<%= link_to 'Exibir', @category %> |
<%= link_to 'Voltar', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categorias</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= link_to 'Alterar', edit_category_path(category) %></td>
        <td><%= link_to 'Excluir', category, method: :delete, data: { confirm: 'Tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nova Categoria', new_category_path %>

app/views/categories/new.html.erb
<h1>Nova Categoria</h1>

<%= render 'form', category: @category %>

<%= link_to 'Voltar', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @category.name %>
</p>

<%= link_to 'Alterar', edit_category_path(@category) %> |
<%= link_to 'Voltar', categories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LinkRepo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p>
      <strong> <%= link_to 'Links', links_path %> </strong>
      <strong> <%= link_to 'Categoria', categories_path %> </strong>
    </p>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/links/_form.html.erb
<%= form_with(model: link, local: true) do |form| %>
  <% if link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% link.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
	Título
    <%= form.text_field :title, id: :link_title %>
  </div>

  <div class="field">
	URL
    <%= form.text_field :url, id: :link_url %>
  </div>

  <div>
    <p><img id="preview-img" width="200px" height="184px"></p>
    <h4 id="preview-title"></h4>
    <p id="preview-description"></p>
  </div>

  <div class="field">
	Categoria
	<%= form.collection_select(:category_id, Category.all, :id, :name) %>
  <%= link_to 'Nova Categoria', new_category_path %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/links/create.html.erb
<h1>Links#create</h1>
<p>Find me in app/views/links/create.html.erb</p>

app/views/links/destroy.html.erb
<h1>Links#destroy</h1>
<p>Find me in app/views/links/destroy.html.erb</p>

app/views/links/edit.html.erb
<h1>Alterando Link</h1>

<%= render 'form', link: @link %>

<%= link_to 'Exibir', @link %> |
<%= link_to 'Voltar', links_path %>

app/views/links/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Links</h1>

<%= form_tag(links_path, method: :get) do %>
  <%= text_field_tag :title, params[:title] %>
  <%= submit_tag 'Buscar', name: nil %>
<% end %>
<table>
  <thead>
    <tr>
      <th>Título</th>
      <th>Lido?</th>
      <th>Categoria</th>
      <th colspan="3"></th>
    </tr>
    <tr>
      <td>
      </td>
    </tr>
  </thead>

  <% if @links %>
    <tbody id="app">
      <% @links.each do |link| %>
	  <tr id='<%= link.id %>'>
          <td><%= link_to link.title, link.url %></td>
		  <td class="read">
			  <input type="checkbox"
				  <% if link.read %>
					checked
				  <% end %>
			  >
		  </td>
          <td><%= link.category.name %></td>
          <td><%= link_to 'Alterar', edit_link_path(link) %></td>
          <td><%= link_to 'Excluir', link, method: :delete, data: { confirm: 'Tem certeza?' } %></td>
        </tr>
      <% end %>
    </tbody>
  <%end%>
</table>

<br>

<script>

</script>

<%= link_to 'Novo Link', new_link_path %>

app/views/links/new.html.erb
<h1>Novo Link</h1>

<%= render 'form', link: @link %>

<%= link_to 'Voltar', links_path %>

app/views/links/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Título:</strong>
  <%= @link.title %>
</p>

<p>
  <strong>Url:</strong>
  <%= link_to @link.url %>
</p>

<p>
  <strong>Lido:</strong>
  <%= readable_boolean(@link.read) %>
</p>

<p>
  <strong>Categoria:</strong>
  <%= @link.category.name %>
</p>

<%= link_to 'Alterar', edit_link_path(@link) %> |
<%= link_to 'Voltar', links_path %>

app/views/links/update.html.erb
<h1>Links#update</h1>
<p>Find me in app/views/links/update.html.erb</p>